language: android
jdk: oraclejdk8
sudo: false
git:
  depth:3

android:
   components:
      - tools
#      - platform-tools
#      - tools

      # The BuildTools version used by your project
      - build-tools-26.0.1

      # The SDK version used to compile your project
      - android-26
      - extra-android-m2repository
      - extra-android-support

  deploy:
    provider: releases
    file: TravisExample.apk
    skip_cleanup: true

  script:
    - "./gradlew assembleRelease"

  before_install:
    - chmod +x gradlew




